### ISSUE TITLE
Get Live Stream

### ISSUE THREAD

**Issue by MrMahdi313** [ping/instagram_private_api_extensions#12]
Can i start live stream from own account from this lib?

**Comment by ping** [comment]
@MrMahdi313

Your issue report does not conform to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api_extensions/master/.github/ISSUE_TEMPLATE.md

Please edit your issue to comply with the template requirement.

This issue will be closed after 24 hours if no followup action is taken.

--------------------------------------------------
[This comment is auto-generated. ref=notemplate]
