### ISSUE TITLE
Update Moviepy package to the current stable version.

### ISSUE THREAD

**Issue by Kaszanas** [ping/instagram_private_api_extensions#17]
Hello!
I have read the code in this repository and I only see 1 place where moviepy package is used.
In my current project I have already implemented Moviepy v1.0.0 and the current released stable version of this package is 1.0.1

I have checked the scripts using moviepy and I am confident that those should work on version 1.0.0

**Comment by ping** [comment]
Your issue report has been closed for not conforming to the issue template that has been specified for this repo:
https://raw.githubusercontent.com/ping/instagram_private_api_extensions/master/.github/ISSUE_TEMPLATE.md
