### ISSUE TITLE
Support up-scaling of media to meet requirements.

### ISSUE THREAD

**Issue by BitJunky** [ping/instagram_private_api_extensions#2]
I tried to upload a video of smaller width but it just rejected it. Kindly support up scaling to meet the requirements.

**Comment by ping** [comment]
You can now specify a custom ``min_size`` argument in ``prepare_image()``/``prepare_video()``. The default min_size values should also work.

**Comment by neFAST** [comment]
Sorry to necro this one, but it seems that with rounding error, scaling is not working properly. At least I got an image scaled to default max ratio (0,75) which ended with a ratio of 0,7501.... and got rejected by Instagram
