### ISSUE TITLE
instagram live broadcast

### ISSUE THREAD

**Issue by kirkaig32** [ping/instagram_private_api_extensions#3]
how do you get the broadcast id for live broadcasts?

**Comment by ping** [comment]
You need to use [instagram_private_api](https://github.com/ping/instagram_private_api). This repo is an extension module to that.

https://instagram-private-api.readthedocs.io/en/latest/api.html#instagram_private_api.Client.discover_top_live
or
https://instagram-private-api.readthedocs.io/en/latest/api.html#instagram_private_api.Client.user_story_feed
